export function getNotes() {
  return [
    {
      id: 'project-brainstorming',
      title: 'Project Brainstorming',
      excerpt: 'Looking into the new workspace layout. We need more focus zones and collaborative pods. Consider adjustable standing desks for fluid typography and a strictly light-mode first system.',
      date: 'Oct 24, 10:45 AM',
      relativeTime: '2 hours ago',
      icon: 'pin',
      tags: ['Work', 'Strategy'],
      favorite: true,
      type: 'text',
    },
    {
      id: 'weekend-trip',
      title: 'Weekend Trip Ideas',
      excerpt: 'Check out the coastal hiking trails. Maybe book that cabin near the Big Sur lighthouse. Do not forget to pack the heavy-duty binoculars for the early overlook.',
      date: 'Monday',
      relativeTime: 'Yesterday',
      icon: 'star',
      tags: ['Travel'],
      favorite: true,
      type: 'text',
    },
    {
      id: 'grocery-list',
      title: 'Grocery List',
      excerpt: 'Oat milk, avocados, sourdough bread, almond butter, and those specific dark chocolate sea salt bars that Sarah likes.',
      date: 'Yesterday',
      relativeTime: '3 days ago',
      icon: 'basket-outline',
      tags: ['Home'],
      favorite: true,
      type: 'checklist',
    },
    {
      id: 'minimal-design',
      title: 'The Future of Minimal Design',
      excerpt: 'Minimalism is not just about removing things; it is about making what remains more powerful. We should explore high-contrast typography and intentional whitespace.',
      date: 'Last Week',
      relativeTime: 'Last Week',
      icon: 'create-outline',
      tags: ['Article', 'Design'],
      favorite: false,
      type: 'article',
    },
    {
      id: 'creative-prompts',
      title: 'Creative Writing Prompts',
      excerpt: 'Drafting the first chapter of the new sci-fi short story. Start with the quiet room, then let the discovery arrive through a small impossible detail.',
      date: 'Oct 20, 2023',
      relativeTime: 'Oct 20',
      icon: 'image-outline',
      tags: ['Writing'],
      favorite: false,
      type: 'image',
    },
    {
      id: 'meeting-q4',
      title: 'Meeting Notes: Q4 Review',
      excerpt: 'Attendance: Sarah, Mike, Jane. Key takeaway: User engagement is up 12% following the minimalist UI redesign.',
      date: 'Oct 18, 4:15 PM',
      relativeTime: 'Oct 18',
      icon: 'people-outline',
      tags: ['Work'],
      favorite: false,
      type: 'meeting',
    },
  ];
}
